[package]
name = "winui_gallery"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false

[package.metadata.inset]
identifier = "rs.inset.winui-gallery"
name = "WinUI Gallery"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
inset.workspace = true
inset-winui.workspace = true
inset-embedder.workspace = true
inset-foundation.workspace = true
inset-painting.workspace = true
inset-rendering.workspace = true
inset-shell.workspace = true
inset-widgets.workspace = true
[dev-dependencies]
inset-animation.workspace = true
inset-test.workspace = true
inset-services.workspace = true
inset-gestures.workspace = true
inset-scheduler.workspace = true
inset-winui-test-support.workspace = true
[lints]
workspace = true

[[bin]]
name = "winui-gallery"
path = "src/main.rs"
