[package]
name = "winui_gallery"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true
[dependencies]
inset-winui.workspace = true
inset-embedder.workspace = true
inset-embedder-winit.workspace = true
inset-foundation.workspace = true
inset-painting.workspace = true
inset-rendering.workspace = true
inset-shell.workspace = true
inset-widgets.workspace = true
[dev-dependencies]
inset-animation.workspace = true
inset-services.workspace = true
inset-gestures.workspace = true
inset-scheduler.workspace = true
valo-harness.workspace = true
[lints]
workspace = true

[[bin]]
name = "winui-gallery"
path = "src/main.rs"
