[package]
name = "reveal-winui"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
reveal-animation.workspace = true
reveal-embedder.workspace = true
reveal-foundation.workspace = true
reveal-gestures.workspace = true
reveal-painting.workspace = true
reveal-rendering.workspace = true
reveal-scheduler.workspace = true
reveal-services.workspace = true
reveal-widgets.workspace = true

[lints]
workspace = true
