[package]
name = "inset-winui"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
inset-animation.workspace = true
inset-embedder.workspace = true
inset-foundation.workspace = true
inset-gestures.workspace = true
inset-painting.workspace = true
inset-rendering.workspace = true
inset-scheduler.workspace = true
inset-services.workspace = true
inset-widgets.workspace = true

[lints]
workspace = true
